name: inha_task
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^1.0.4
  flutter_screenutil: ^5.5.4
  smooth_page_indicator: ^1.0.0+2
  animate_do: ^2.1.0
  flutter_secure_storage: ^6.0.0
  local_auth: ^2.1.2
  credit_card_scanner: ^1.0.5
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Mont.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

